############################################################
# 03_mouse_validation.R
#
# Purpose:
# Validate human macrophage-associated targets in an
# independent mouse lupus nephritis scRNA-seq dataset
# (GSE201932).
############################################################

library(Seurat)
library(dplyr)
library(tibble)
library(ggplot2)

############################################################
# Load mouse atlas
############################################################

mouse_ln <- readRDS(
  "GSE201932_mouse_validated_atlas.rds"
)

mouse_ln

############################################################
# Identify mouse macrophage cluster
############################################################

table(Idents(mouse_ln))

mouse_macrophages <- subset(
  mouse_ln,
  idents = "9"
)

table(mouse_macrophages$Condition)

############################################################
# Mouse macrophage differential expression
############################################################

Idents(mouse_macrophages) <- "Condition"

macrophage_DE <- FindMarkers(
  mouse_macrophages,
  ident.1 = "MRL_lpr",
  ident.2 = "Control",
  only.pos = TRUE
)

head(macrophage_DE)

macrophage_DE <- macrophage_DE %>%
  tibble::rownames_to_column("Gene")

write.csv(
  macrophage_DE,
  "results/Mouse_Macrophage_MRLlpr_vs_Control.csv",
  row.names = FALSE
)

############################################################
# Cross-species target validation
############################################################

mouse_target_panel <- c(
  "C5ar1", "C3ar1", "Csf1r", "Tlr4",
  "P2rx7", "Clec7a", "Siglec1", "Pilra",
  "Lilrb4a", "Cd300e", "C1qa", "Lyz2"
)

avg_mouse_targets <- AverageExpression(
  mouse_ln,
  features = mouse_target_panel,
  group.by = "seurat_clusters"
)$RNA

avg_mouse_cluster9 <- avg_mouse_targets[, "g9"]

avg_mouse_cluster9

write.csv(
  data.frame(
    Gene = names(avg_mouse_cluster9),
    Mouse_Macrophage_Cluster9_Expression = as.numeric(avg_mouse_cluster9)
  ),
  "results/Mouse_Target_Expression_Cluster9.csv",
  row.names = FALSE
)

############################################################
# Exploratory mouse candidate-target figure
#
# This broader panel is retained as a supplementary figure.
# The main cross-dataset comparison of the four final targets
# is generated by 05_consensus_ranking.R.
############################################################

DotPlot(
  mouse_ln,
  features = c("C5ar1", "Csf1r", "C3ar1", "P2rx7", "Clec7a", "Pilra")
) +
  RotatedAxis()

png(
  "figures/Supplementary_Figure1_Mouse_Candidate_Targets_DotPlot.png",
  width = 2400,
  height = 1500,
  res = 300
)

DotPlot(
  mouse_ln,
  features = c("C5ar1", "Csf1r", "C3ar1", "P2rx7", "Clec7a", "Pilra")
) +
  RotatedAxis()

dev.off()